name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  camera: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/jacket.png
  - assets/images/skirt.png
  - assets/images/invisible.png
  - assets/images/jeans.png
  - assets/images/womens_blouse.png
  - assets/images/wedding_dress.png
  - assets/images/signal.png
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/group_16_x2.svg
  - assets/vectors/component_115_x2.svg
  - assets/vectors/wifi_8_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/images/women_shorts_id_00007338021_front.png
  - assets/images/invisible.png
  - assets/images/wedding_dress.png
  - assets/images/women_shorts_id_00007560011_front.png
  - assets/images/women_shorts_id_00007792071_front.png
  - assets/images/skirt.png
  - assets/images/women_shorts_id_00007513011_front.png
  - assets/images/jeans.png
  - assets/images/women_shorts_id_00007345021_front.png
  - assets/images/womens_blouse.png
  - assets/images/women_shorts_id_00006716011_front.png
  - assets/images/jacket.png
  - assets/images/signal.png
  - assets/vectors/wifi_29_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/component_128_x2.svg
  - assets/images/women_dresses_id_00000872021_front.png
  - assets/images/women_shorts_id_00006716011_front.png
  - assets/images/women_jackets_coats_id_00005652031_front.png
  - assets/images/jacket.png
  - assets/images/women_jackets_coats_id_00007722021_front.png
  - assets/images/women_dresses_id_00000811044_full.png
  - assets/images/women_shorts_id_00007792071_front.png
  - assets/images/ophthalmology.png
  - assets/images/women_dresses_id_00001323011_front.png
  - assets/images/skirt.png
  - assets/images/women_blouses_shirts_id_00002481017_additional.png
  - assets/images/women_jackets_coats_id_00007734011_front.png
  - assets/images/women_skirts_id_00001771021_front.png
  - assets/images/women_dresses_id_00001267031_front.png
  - assets/images/women_blouses_shirts_id_00002330031_front.png
  - assets/images/women_blouses_shirts_id_00001969011_front.png
  - assets/images/women_jackets_coats_id_00007480011_front.png
  - assets/images/jeans.png
  - assets/images/women_skirts_id_00006463061_front.png
  - assets/images/women_blouses_shirts_id_00002246011_front.png
  - assets/images/signal.png
  - assets/images/women_shorts_id_00007513011_front.png
  - assets/images/women_shorts_id_00007338021_front.png
  - assets/images/women_blouses_shirts_id_00001616011_front.png
  - assets/images/women_jackets_coats_id_00005411021_front.png
  - assets/images/women_skirts_id_00004114011_front.png
  - assets/images/women_skirts_id_00005944023_back.png
  - assets/images/women_shorts_id_00007345021_front.png
  - assets/images/women_skirts_id_00001333051_front.png
  - assets/images/women_blouses_shirts_id_00002485011_front.png
  - assets/images/wedding_dress.png
  - assets/images/women_shorts_id_00007560011_front.png
  - assets/images/women_dresses_id_00000852051_front.png
  - assets/images/women_dresses_id_00000731121_front.png
  - assets/images/women_skirts_id_00006463071_front.png
  - assets/images/women_jackets_coats_id_00006337021_front.png
  - assets/images/womens_blouse.png
  - assets/vectors/group_13_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/component_18_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/wifi_7_x2.svg
  - assets/images/signal.png
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/wifi_17_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/component_110_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/images/signal.png
  - assets/images/desain_tanpa_judul_83.png
  - assets/vectors/flat_color_iconsgoogle_1_x2.svg
  - assets/vectors/wifi_27_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/component_126_x2.svg
  - assets/images/men_pants_id_00000114011_front.png
  - assets/images/jacket.png
  - assets/images/men_pants_id_00000494011_front.png
  - assets/images/signal.png
  - assets/images/sweater.png
  - assets/images/invisible.png
  - assets/images/men_pants_id_00004788031_front.png
  - assets/images/tshirt.png
  - assets/images/men_pants_id_00006697014_full.png
  - assets/images/denim_shorts.png
  - assets/images/men_pants_id_00007323011_front.png
  - assets/images/men_pants_id_00000494041_front.png
  - assets/images/jeans.png
  - assets/vectors/component_121_x2.svg
  - assets/vectors/wifi_9_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/group_15_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/images/desain_tanpa_judul_83.png
  - assets/images/signal.png
  - assets/vectors/wifi_22_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/component_112_x2.svg
  - assets/images/signal.png
  - assets/images/whats_app_image_20240521_at_14131.jpeg
  - assets/images/compact_camera.png
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/component_117_x2.svg
  - assets/vectors/wifi_11_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/images/men_pants_id_00007323011_front.png
  - assets/images/men_pants_id_00006697014_full.png
  - assets/images/denim_shorts.png
  - assets/images/men_shorts_id_00007496014_full.png
  - assets/images/tshirt.png
  - assets/images/men_jackets_vests_id_00000084041_front.png
  - assets/images/men_shorts_id_00006143037_additional.png
  - assets/images/men_shirts_polos_id_00003131011_front.png
  - assets/images/men_pants_id_00000494011_front.png
  - assets/images/men_shirts_polos_id_00003489131_front.png
  - assets/images/men_shorts_id_00007496034_full.png
  - assets/images/men_sweatshirts_hoodies_id_00006807011_front.png
  - assets/images/ophthalmology.png
  - assets/images/men_pants_id_00000114011_front.png
  - assets/images/men_sweatshirts_hoodies_id_00002977011_front.png
  - assets/images/men_shorts_id_00007128027_additional.png
  - assets/images/signal.png
  - assets/images/men_pants_id_00004788031_front.png
  - assets/images/men_shirts_polos_id_00000226041_front.png
  - assets/images/jeans.png
  - assets/images/men_sweatshirts_hoodies_id_00005144051_front.png
  - assets/images/men_shorts_id_00007539017_additional.png
  - assets/images/men_shirts_polos_id_00000240011_front.png
  - assets/images/men_pants_id_00000494041_front.png
  - assets/images/men_shirts_polos_id_00003329011_front.png
  - assets/images/men_jackets_vests_id_00005528094_full.png
  - assets/images/men_shirts_polos_id_00000711011_front.png
  - assets/images/sweater.png
  - assets/images/men_jackets_vests_id_00005943091_front.png
  - assets/images/men_jackets_vests_id_00000168031_front.png
  - assets/images/men_sweatshirts_hoodies_id_00002115011_front.png
  - assets/images/men_sweatshirts_hoodies_id_00007613011_front.png
  - assets/images/men_jackets_vests_id_00002754014_full.png
  - assets/images/jacket.png
  - assets/images/men_shorts_id_00006745014_full.png
  - assets/images/men_jackets_vests_id_00007569041_front.png
  - assets/images/men_sweatshirts_hoodies_id_00000978021_front.png
  - assets/vectors/group_5_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/component_14_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/images/signal.png
  - assets/images/men_shirts_polos_id_00000226041_front.png
  - assets/images/invisible.png
  - assets/images/jeans.png
  - assets/images/jacket.png
  - assets/images/men_shirts_polos_id_00003489131_front.png
  - assets/images/men_shirts_polos_id_00003329011_front.png
  - assets/images/sweater.png
  - assets/images/men_shirts_polos_id_00000240011_front.png
  - assets/images/men_shirts_polos_id_00003131011_front.png
  - assets/images/men_shirts_polos_id_00000711011_front.png
  - assets/images/tshirt.png
  - assets/images/denim_shorts.png
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/component_119_x2.svg
  - assets/vectors/group_4_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/images/desain_tanpa_judul_83.png
  - assets/images/signal.png
  - assets/vectors/wifi_20_x2.svg
  - assets/vectors/component_15_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/images/signal.png
  - assets/images/desain_tanpa_judul_83.png
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/component_12_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/flat_color_iconsgoogle_x2.svg
  - assets/images/invisible.png
  - assets/images/men_jackets_vests_id_00005943091_front.png
  - assets/images/sweater.png
  - assets/images/signal.png
  - assets/images/tshirt.png
  - assets/images/men_jackets_vests_id_00000084041_front.png
  - assets/images/jeans.png
  - assets/images/jacket.png
  - assets/images/men_jackets_vests_id_00007569041_front.png
  - assets/images/denim_shorts.png
  - assets/images/men_jackets_vests_id_00002754014_full.png
  - assets/images/men_jackets_vests_id_00000168031_front.png
  - assets/images/men_jackets_vests_id_00005528094_full.png
  - assets/vectors/component_19_x2.svg
  - assets/vectors/group_7_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/wifi_16_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/images/jacket.png
  - assets/images/men_sweatshirts_hoodies_id_00002115011_front.png
  - assets/images/men_sweatshirts_hoodies_id_00007613011_front.png
  - assets/images/men_sweatshirts_hoodies_id_00002977011_front.png
  - assets/images/men_sweatshirts_hoodies_id_00006807011_front.png
  - assets/images/sweater.png
  - assets/images/denim_shorts.png
  - assets/images/invisible.png
  - assets/images/tshirt.png
  - assets/images/men_sweatshirts_hoodies_id_00005144051_front.png
  - assets/images/men_sweatshirts_hoodies_id_00000978021_front.png
  - assets/images/jeans.png
  - assets/images/signal.png
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/group_6_x2.svg
  - assets/vectors/wifi_12_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/component_116_x2.svg
  - assets/images/women_dresses_id_00000852051_front.png
  - assets/images/women_dresses_id_00000811041_front.png
  - assets/images/women_dresses_id_00000872021_front_1.png
  - assets/images/wedding_dress.png
  - assets/images/signal.png
  - assets/images/women_dresses_id_00001267031_front.png
  - assets/images/skirt.png
  - assets/images/jacket.png
  - assets/images/invisible.png
  - assets/images/women_dresses_id_00000731121_front.png
  - assets/images/women_dresses_id_00001323011_front.png
  - assets/images/jeans.png
  - assets/images/womens_blouse.png
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/group_12_x2.svg
  - assets/vectors/component_11_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/wifi_21_x2.svg
  - assets/images/signal.png
  - assets/vectors/component_1_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/wifi_6_x2.svg
  - assets/images/compact_camera.png
  - assets/images/whats_app_image_20240521_at_14131.jpeg
  - assets/images/signal.png
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/wifi_18_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/component_113_x2.svg
  - assets/images/image.png
  - assets/images/image_2.png
  - assets/images/jeans.png
  - assets/images/women_skirts_id_00001771021_front.png
  - assets/images/desain_tanpa_judul_101.png
  - assets/images/skirt.png
  - assets/images/image_1.png
  - assets/images/invisible.png
  - assets/images/womens_blouse.png
  - assets/images/desain_tanpa_judul_91.png
  - assets/images/desain_tanpa_judul_111.png
  - assets/images/signal.png
  - assets/images/wedding_dress.png
  - assets/images/jacket.png
  - assets/vectors/group_9_x2.svg
  - assets/vectors/wifi_13_x2.svg
  - assets/vectors/component_127_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/images/sweater.png
  - assets/images/jeans.png
  - assets/images/tshirt.png
  - assets/images/denim_shorts.png
  - assets/images/signal.png
  - assets/images/invisible.png
  - assets/images/jacket.png
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/component_13_x2.svg
  - assets/vectors/group_8_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/images/desain_tanpa_judul_83.png
  - assets/images/signal.png
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/wifi_23_x2.svg
  - assets/vectors/component_114_x2.svg
  - assets/images/invisible.png
  - assets/images/women_skirts_id_00004114011_front.png
  - assets/images/women_blouses_shirts_id_00002246011_front_1.png
  - assets/images/jacket.png
  - assets/images/wedding_dress.png
  - assets/images/women_skirts_id_00005944021_front.png
  - assets/images/women_skirts_id_00006463061_front.png
  - assets/images/jeans.png
  - assets/images/women_skirts_id_00006463071_front.png
  - assets/images/women_skirts_id_00001333051_front.png
  - assets/images/signal.png
  - assets/images/skirt.png
  - assets/images/womens_blouse.png
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/component_122_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/wifi_10_x2.svg
  - assets/images/women_blouses_shirts_id_00002246011_front.png
  - assets/images/signal.png
  - assets/images/jacket.png
  - assets/images/invisible.png
  - assets/images/jeans.png
  - assets/images/wedding_dress.png
  - assets/images/skirt.png
  - assets/images/women_blouses_shirts_id_00002485011_front.png
  - assets/images/womens_blouse.png
  - assets/images/women_blouses_shirts_id_00002330031_front.png
  - assets/images/women_blouses_shirts_id_00002481017_additional.png
  - assets/images/women_blouses_shirts_id_00001616011_front.png
  - assets/images/women_blouses_shirts_id_00001969011_front.png
  - assets/vectors/wifi_19_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/group_14_x2.svg
  - assets/vectors/component_129_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/images/signal.png
  - assets/images/desain_tanpa_judul_83.png
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/wifi_28_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/component_123_x2.svg
  - assets/images/compact_camera.png
  - assets/images/whats_app_image_20240521_at_14131.jpeg
  - assets/images/signal.png
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/wifi_26_x2.svg
  - assets/vectors/component_124_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/images/signal.png
  - assets/images/compact_camera.png
  - assets/images/whats_app_image_20240521_at_14131.jpeg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/component_17_x2.svg
  - assets/vectors/wifi_15_x2.svg
  - assets/images/signal.png
  - assets/images/compact_camera.png
  - assets/images/whats_app_image_20240521_at_14131.jpeg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/component_16_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/images/user_male.png
  - assets/images/female_user.png
  - assets/images/signal.png
  - assets/vectors/component_125_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/wifi_25_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/group_10_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/images/jacket.png
  - assets/images/men_shorts_id_00006143037_additional.png
  - assets/images/men_shorts_id_00007128027_additional.png
  - assets/images/men_shorts_id_00006745014_full.png
  - assets/images/men_shorts_id_00007496034_full.png
  - assets/images/signal.png
  - assets/images/jeans.png
  - assets/images/denim_shorts.png
  - assets/images/men_shorts_id_00007496014_full.png
  - assets/images/men_shorts_id_00007539017_additional.png
  - assets/images/invisible.png
  - assets/images/tshirt.png
  - assets/images/sweater.png
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/component_111_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/group_11_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/images/desain_tanpa_judul_83.png
  - assets/images/signal.png
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/wifi_24_x2.svg
  - assets/vectors/component_118_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/images/whats_app_image_20240521_at_14131.jpeg
  - assets/images/compact_camera.png
  - assets/images/signal.png
  - assets/vectors/component_120_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/wifi_14_x2.svg
  - assets/vectors/vector_93_x2.svg

